/* Morpheus MD: funciona sin internet. Guarda la app en caché la primera vez que se abre. */
const VERSION = 'morpheus-1.9.12';
const ARCHIVOS = [
  './',
  'css/app.css',
  'fonts/cormorant-garamond-latin-400-italic.woff2',
  'fonts/cormorant-garamond-latin-400-normal.woff2',
  'fonts/cormorant-garamond-latin-600-normal.woff2',
  'img/bloqueos/antebrazo-1.jpg',
  'img/bloqueos/axilar-1.jpg',
  'img/bloqueos/canal-aductor-1.jpg',
  'img/bloqueos/canal-aductor-2.jpg',
  'img/bloqueos/caudal-1.jpg',
  'img/bloqueos/caudal-2.jpg',
  'img/bloqueos/ciatico-proximal-1.jpg',
  'img/bloqueos/costoclavicular-1.jpg',
  'img/bloqueos/cuadrado-lumbar-1.jpg',
  'img/bloqueos/cuadrado-lumbar-2.jpg',
  'img/bloqueos/cutaneo-femoral-lateral-1.jpg',
  'img/bloqueos/cutaneo-femoral-lateral-2.jpg',
  'img/bloqueos/esp-1.jpg',
  'img/bloqueos/esp-2.jpg',
  'img/bloqueos/fascia-iliaca-1.jpg',
  'img/bloqueos/fascia-iliaca-2.jpg',
  'img/bloqueos/fascia-transversalis-1.jpg',
  'img/bloqueos/femoral-1.jpg',
  'img/bloqueos/ilioinguinal-1.jpg',
  'img/bloqueos/ilioinguinal-2.jpg',
  'img/bloqueos/infraclavicular-1.jpg',
  'img/bloqueos/intercostal-1.jpg',
  'img/bloqueos/intercostal-2.jpg',
  'img/bloqueos/interescalenico-1.jpg',
  'img/bloqueos/ipack-1.jpg',
  'img/bloqueos/obturador-1.jpg',
  'img/bloqueos/obturador-2.jpg',
  'img/bloqueos/oftalmicos-1.jpg',
  'img/bloqueos/paraesternal-1.jpg',
  'img/bloqueos/paraesternal-2.jpg',
  'img/bloqueos/paravertebral-1.jpg',
  'img/bloqueos/paravertebral-2.jpg',
  'img/bloqueos/pecs-1.jpg',
  'img/bloqueos/pecs-2.jpg',
  'img/bloqueos/pene-1.jpg',
  'img/bloqueos/pene-2.jpg',
  'img/bloqueos/peng-1.jpg',
  'img/bloqueos/plexo-cervical-1.jpg',
  'img/bloqueos/plexo-cervical-2.jpg',
  'img/bloqueos/popliteo-1.jpg',
  'img/bloqueos/popliteo-2.jpg',
  'img/bloqueos/serrato-1.jpg',
  'img/bloqueos/supraclavicular-1.jpg',
  'img/bloqueos/supraescapular-1.jpg',
  'img/bloqueos/tap-1.jpg',
  'img/bloqueos/tap-2.jpg',
  'img/bloqueos/tobillo-1.jpg',
  'img/bloqueos/triangulo-femoral-1.jpg',
  'img/bloqueos/tronco-superior-1.jpg',
  'img/bloqueos/tronco-superior-2.jpg',
  'img/bloqueos/vaina-rectos-1.jpg',
  'img/bloqueos/vaina-rectos-2.jpg',
  'img/bloqueos/via-aerea-1.jpg',
  'img/icono-192.png',
  'img/icono-512-mask.png',
  'img/icono-512.png',
  'img/portada.jpg',
  'index.html',
  'js/app.js',
  'js/bloqueos-datos.js',
  'js/calc.js',
  'js/crisis.js',
  'js/cuenta.js',
  'js/extras.js',
  'js/fuentes.js',
  'js/guias-datos.js',
  'js/imgs.js',
  'js/legal.js',
  'js/obs.js',
  'js/pdf.js',
  'js/pistas.js',
  'js/store.js',
  'js/visor.js',
  'lib/jspdf.umd.min.js',
  'lib/pdfjs/pdf.min.js',
  'lib/pdfjs/pdf.worker.min.js',
  'manifest.webmanifest'
];
self.addEventListener('install', (e) => { e.waitUntil(caches.open(VERSION).then((c) => c.addAll(ARCHIVOS)).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((r) => r || fetch(e.request).then((res) => {
    if (res.ok && new URL(e.request.url).origin === location.origin) { const copia = res.clone(); caches.open(VERSION).then((c) => c.put(e.request, copia)); }
    return res;
  })));
});
